force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Acceptance_Rate__c.field-meta.xml
<CustomField>
    <fullName>Acceptance_Rate__c</fullName>
    <formula>IF( Acceptances__c = 0, 0, (Acceptances__c  /  (  Acceptances__c  +  Rejections__c  )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Acceptance Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Acceptances__c.field-meta.xml
<CustomField>
    <fullName>Acceptances__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Acceptances</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <defaultValue>&apos;https://c.ap2.visual.force.com/resource/1474479881000/default&apos;</defaultValue>
    <label>Attachment</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Available_Deals__c.field-meta.xml
<CustomField>
    <fullName>Available_Deals__c</fullName>
    <formula>Max_Acceptances__c  -  Acceptances__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Deals</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Rejections__c.field-meta.xml
<CustomField>
    <fullName>Rejections__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rejections</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Valid_Through__c.field-meta.xml
<CustomField>
    <fullName>Valid_Through__c</fullName>
    <label>Valid Through</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal_Action__c/Deal_Action__c.object-meta.xml
<CustomObject>
    <label>Deal Action</label>
    <nameField>
        <displayFormat>DA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deal Actions</relationshipLabel>
    <relationshipName>Contact_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Action__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal Actions</relationshipLabel>
    <relationshipName>Deal_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Action__c/fields/Disable_Status__c.field-meta.xml
<CustomField>
    <fullName>Disable_Status__c</fullName>
    <formula>IF( ISPICKVAL(Action__c , &apos;Available&apos;) , &apos;false&apos;, &apos;true&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Disable Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactExtension.cls
public class ContactExtension {
        
    //public List<Deal_Action__c> dealAction {get;set;}
    public Deal__c deal;
    public Deal_Action__c dealAc;
    public Contact cont;
    
    
    
    public ContactExtension(ApexPages.StandardController controller) {
             
        this.cont = (Contact)controller.getRecord(); 
        
        // dealAction = [SELECT id, Name, Action__c, Deal__c, Contact__c, Disable_Status__c, Deal__r.Valid_Through__c, 
        //                   Deal__r.Available_Deals__c, Deal__r.Attachment__c FROM Deal_Action__c];         
        
    }
    
    
    public List<Deal_Action__c> getdealAction(){
        
        List<Deal_Action__c> lstDealActions = new List<Deal_Action__c>();
        lstDealActions = [SELECT id, Name, Action__c, Deal__c, Contact__c, Disable_Status__c, Deal__r.Valid_Through__c, 
                           Deal__r.Available_Deals__c, Deal__r.Attachment__c FROM Deal_Action__c];
        return lstDealActions;                           
    } 
    
    public Contact getContact(){
        return [select Name, Acceptance_Rate__c, Deals_Accepted__c, Deals_Rejected__c FROM Contact Where id=: cont.id];
    }
    
    public PageReference navigateToContactDetail(){
        
        PageReference pr = new PageReference('/'+cont.id);
        pr.setRedirect(true);
        return pr;
        
    }
    
    
    public String acceptMethod(){
        
        String dealAId = ApexPages.CurrentPage().getParameters().get('dAId');
        
        dealAc = [SELECT Name, Action__c, Deal__c  FROM Deal_Action__c 
                     WHERE ID = : dealAId];
        dealAc.Action__c = 'Accepted';
        dealAc.Contact__c = cont.id;
        update dealAc;
        
        Deal_Action__c newDA = new Deal_Action__c(Deal__c = dealAc.Deal__c, Action__c = 'Available'); 
        insert newDA;
        
        system.debug('debugme....dealname from deal_action ---- '+dealAc.Deal__c);
        
        deal = [SELECT Name,Acceptances__c  FROM Deal__c 
                     WHERE id = : dealAc.Deal__c];
        
        system.debug('debugme....dealname---- '+deal.name);             
                     
        deal.Acceptances__c += 1;              
        update deal;             
         
                  
        cont.Deals_Accepted__c += 1; 
        update cont; 
                   
        
        return null;
    }
    
    public String rejectMethod(){
        
        String dealAId = ApexPages.CurrentPage().getParameters().get('dAId');
        
        dealAc = [SELECT Name, Action__c, Deal__c  FROM Deal_Action__c 
                     WHERE ID = : dealAId];
        dealAc.Action__c = 'Rejected';
        dealAc.Contact__c = cont.id;
        update dealAc;
        
        Deal_Action__c newDA = new Deal_Action__c(Deal__c = dealAc.Deal__c, Action__c = 'Available'); 
        insert newDA;
        
        deal = [SELECT Name,Rejections__c  FROM Deal__c 
                     WHERE id = : dealAc.Deal__c];                
        deal.Rejections__c += 1;              
        update deal;             
         
                  
        cont.Deals_Rejected__c += 1; 
        update cont; 
                
        
        return null;
    }
    
    

}